"""Agent tool: generate a structured markdown report from document content."""

from langchain.tools import tool
from sqlalchemy.orm import Session


def make_export_tool(db: Session, document_ids: list[str] | None = None):
    """Factory that returns an export tool bound to a db session."""

    @tool
    def export_report(report_request: str) -> str:
        """
        Generate a structured, exportable report from document content.
        Use this when the user asks to generate a report, create a document,
        write a briefing, or produce a structured output from the documents.
        Input: describe the report to generate, e.g. 'executive summary of all documents'
               or 'technical report on the findings in the research papers'.
        Output: a fully formatted markdown report ready for export.
        """
        from app.models.db import Document, DocumentChunk
        from app.services.llm import generate_response
        from uuid import UUID
        from datetime import datetime

        # Get documents
        query = db.query(Document).filter(Document.status == "ready")
        if document_ids:
            doc_uuids = [UUID(d) for d in document_ids]
            query = query.filter(Document.id.in_(doc_uuids))

        docs = query.all()
        if not docs:
            return "No documents available to generate a report from."

        # Collect content from all documents
        all_content = []
        for doc in docs[:5]:  # Cap at 5 docs
            chunks = (
                db.query(DocumentChunk)
                .filter(DocumentChunk.document_id == doc.id)
                .order_by(DocumentChunk.chunk_index)
                .limit(12)
                .all()
            )
            if chunks:
                text = "\n".join(c.content for c in chunks)
                all_content.append(f"SOURCE: {doc.filename}\n{text}")

        combined = "\n\n---\n\n".join(all_content)
        doc_names = ", ".join(d.filename for d in docs)
        today = datetime.now().strftime("%B %d, %Y")

        prompt = f"""You are a professional report writer. Generate a comprehensive, 
well-structured report based on the document content below.

Report requested: {report_request}
Source documents: {doc_names}
Date: {today}

Use this exact structure:
---
# [Report Title]

**Date:** {today}  
**Sources:** {doc_names}  
**Prepared by:** DocMind AI

## Executive Summary
[2-3 paragraph overview]

## Key Findings
[Numbered list of 5-10 key findings with details]

## Detailed Analysis
[Thorough analysis organized by themes/sections]

## Conclusions
[Clear conclusions drawn from the documents]

## Recommendations
[If applicable, actionable recommendations]

---
*This report was auto-generated by DocMind AI from the provided documents.*
---

Document content:
{combined[:9000]}
"""
        result = generate_response(prompt, operation="export_report")

        # Wrap in a special marker so frontend can offer download
        report_text = result["text"]
        return f"REPORT_GENERATED\n{report_text}"

    return export_report
